name: transita_bolivia
description: "Transita Bolivia - App unificada de transporte para pasajeros y conductores"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  qr_flutter: ^4.1.0
  flutter_nfc_kit: ^3.6.2
  ndef: ^0.4.0
  intl: ^0.18.0
  mobile_scanner: ^7.4.0
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#1E88E5"
  adaptive_icon_foreground: "assets/images/logo.png"
